name: Yahoo Scraper

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Yahoo Scraper main.py
      run: |
        python src/edu_pad/main.py

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        git add src/edu_pad/static/db/yahoo_data.db
        git add src/edu_pad/static/csv/yahoo_data.csv

        git commit -m "🤖 Auto-update: Datos generados por scraping [skip ci]" || echo "No hay cambios para commitear"
        git push origin master
